### ISSUE TITLE
Nested sb-admin panel inherit of background color panel-heading

### ISSUE THREAD

**Issue by odurgeau** [BlackrockDigital/startbootstrap-sb-admin-2#120]
For the specific sb-admin panel like panel-green, red and yellow, the css apply the background color of panel-heading likewise at nested panel item, whereas for twitter bootstrap, the panel-primary, by instance, doesn't spread the background-color : 

On twitter bootstrap
```css
.panel-primary > .panel-heading   { .panel-heading-styles(@panel-primary-heading-bg); }
```

On Startbootstrap sb admin 2
```css
.panel-red .panel-heading {
    border-color: #d9534f;
    color: #fff;
    background-color: #d9534f;
}
```

I will make the PR just for that.
