### ISSUE TITLE
Change dropdown colors

### ISSUE THREAD

**Issue by duard** [BlackrockDigital/startbootstrap-sb-admin-2#74]
How can I change this clicked color on this menu ? 
![screen_shot_2015-07-23_at_9_46_41_am](https://cloud.githubusercontent.com/assets/36894/8850618/f10ed64c-311f-11e5-8364-74cd7554688b.png)

**Comment by SemiNormal** [comment]
This should do it: 

```css
.nav .open > a, .nav .open > a:focus, .nav .open > a:hover {
    background-color: #000000;
}
```
